### General Basic Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [122]:
df1= pd.read_csv('Toxtrain.csv')

In [143]:
df = df1[['comment_text','toxic','severe_toxic','obscene','threat','insult','identity_hate']]

In [144]:
from sklearn.cross_validation import train_test_split

In [145]:
X_train.head(10)

toxic  severe_toxic  obscene  threat  insult  identity_hate
78747       0             0        0       0       0              0
8023        0             0        0       0       0              0
81476       0             0        0       0       0              0
54756       0             0        0       0       0              0
84103       0             0        0       0       0              0
66676       0             0        0       0       0              0
129375      0             0        0       0       0              0
23468       0             0        0       0       0              0
70395       0             0        0       0       0              0
72350       0             0        0       0       0              0

In [146]:
X_train.describe


<bound method NDFrame.describe of         toxic  severe_toxic  obscene  threat  insult  identity_hate
78747       0             0        0       0       0              0
8023        0             0        0       0       0              0
81476       0             0        0       0       0              0
54756       0             0        0       0       0              0
84103       0             0        0       0       0              0
66676       0             0        0       0       0              0
129375      0             0        0       0       0              0
23468       0             0        0       0       0              0
70395       0             0        0       0       0              0
72350       0             0        0       0       0              0
21362       0             0        0       0       0              0
141800      0             0        0       0       0              0
53536       0             0        0       0       0              0
76947       0 

In [147]:
X_train.shape


(127656, 6)

In [148]:
X_train.corr()


toxic  severe_toxic   obscene    threat    insult  \
toxic          1.000000      0.309045  0.676405  0.155669  0.647289   
severe_toxic   0.309045      1.000000  0.404448  0.119078  0.375988   
obscene        0.676405      0.404448  1.000000  0.139509  0.741278   
threat         0.155669      0.119078  0.139509  1.000000  0.149442   
insult         0.647289      0.375988  0.741278  0.149442  1.000000   
identity_hate  0.262765      0.199084  0.282233  0.115425  0.334025   

               identity_hate  
toxic               0.262765  
severe_toxic        0.199084  
obscene             0.282233  
threat              0.115425  
insult              0.334025  
identity_hate       1.000000

In [149]:
X_train.info


<bound method DataFrame.info of         toxic  severe_toxic  obscene  threat  insult  identity_hate
78747       0             0        0       0       0              0
8023        0             0        0       0       0              0
81476       0             0        0       0       0              0
54756       0             0        0       0       0              0
84103       0             0        0       0       0              0
66676       0             0        0       0       0              0
129375      0             0        0       0       0              0
23468       0             0        0       0       0              0
70395       0             0        0       0       0              0
72350       0             0        0       0       0              0
21362       0             0        0       0       0              0
141800      0             0        0       0       0              0
53536       0             0        0       0       0              0
76947       0   

In [150]:
X_train.columns


Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [151]:
X_train.groupby(['toxic']).sum()


severe_toxic  obscene  threat  insult  identity_hate
toxic                                                      
0                 0      412      26     433             81
1              1286     6362     358    5905           1022

In [152]:
X_train.groupby(['severe_toxic']).sum()


toxic  obscene  threat  insult  identity_hate
severe_toxic                                               
0             11006     5550     297    5233            857
1              1286     1224      87    1105            246

In [153]:
X_train.groupby(['obscene']).sum()


toxic  severe_toxic  threat  insult  identity_hate
obscene                                                    
0         5930            62     145    1394            297
1         6362          1224     239    4944            806

In [154]:
X_train.groupby(['threat']).sum()


toxic  severe_toxic  obscene  insult  identity_hate
threat                                                     
0       11934          1199     6535    6092           1025
1         358            87      239     246             78

In [155]:
X_train.groupby(['insult']).sum()


toxic  severe_toxic  obscene  threat  identity_hate
insult                                                     
0        6387           181     1830     138            191
1        5905          1105     4944     246            912

In [156]:
X_train.groupby(['identity_hate']).sum()


toxic  severe_toxic  obscene  threat  insult
identity_hate                                              
0              11270          1040     5968     306    5426
1               1022           246      806      78     912

In [157]:
X_train.head()

toxic  severe_toxic  obscene  threat  insult  identity_hate
78747      0             0        0       0       0              0
8023       0             0        0       0       0              0
81476      0             0        0       0       0              0
54756      0             0        0       0       0              0
84103      0             0        0       0       0              0

# NAIVE BAYES CLASSIFIER.

In [158]:
import sklearn
from sklearn.naive_bayes import MultinomialNB
from sklearn import naive_bayes

IMPORTING COUNT VECTORIZER FROM SKLearn

In [159]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

# Predicting Toxic Comments Stepwise

In [160]:
y = df.toxic
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2, random_state = 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING TOXIC
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',ngram_range=(1,2))
 
Toxic_col=X_train.toxic
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Toxic_col.shape)

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)


In [161]:
x

<127656x2373170 sparse matrix of type '<class 'numpy.int64'>'
	with 6977066 stored elements in Compressed Sparse Row format>

### This shows that count vectoriser transforms our training data into a sparse matrix of 159571 rows( Which are the no. of comments in our data) and 189775 columns which are the number of word features.

In [162]:
clf= naive_bayes.MultinomialNB()
clf.fit(x,Toxic_col)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [163]:
X_test.comment_text

38367     whole nickers comment, you deserved it for bei...
81965                  REDIRECT Talk:Lowland red forest rat
23037     I don't want you to keep reverting me, so kind...
40710     Last warning for suppourting sock pupettry \n\...
30075     "\nI believe HC is a talented writer and artis...
76368            , I don't need the archive on the old page
67945     Autofellatio redux \n\nWill, there appears to ...
121171                                Answer: I can't this.
28014     "\n\nOk, Thank you for your help ^_^ ...now ab...
133798    "\n\n You have been reported for Vandalism \n\...
110465    Helen Arthington-Davy\n\nIt seems that Helen A...
51974     Thanks Tim - I'm learning! Quite difficult at ...
128264    You horrid little mincing poofter \n\nI've got...
17581     List of premature obituaries\nHi Jean-Sebastie...
1589      I have proposed some of the latest pic's for I...
96648     Indeed it is not called that, the reason for t...
153277    "Public information is great! 

In [164]:
z=cv.transform(X_test.comment_text)

### Z will give us the sparse matrix for our test data. 

In [165]:
z

<31915x2373170 sparse matrix of type '<class 'numpy.int64'>'
	with 1258701 stored elements in Compressed Sparse Row format>

In [166]:
Toxic_pred=clf.predict(z)
print(Toxic_pred)


[0 0 0 ... 0 0 0]


In [167]:
print(sum(Toxic_pred))

1232


## ABOVE WE GET OUR PREDICTION FOR "TOXIC" COMMENTS IN OUR CORPUS

# SEVERE TOXIC

In [168]:
y = df.severe_toxic
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state= 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
####PREDICTING SEVERE TOXIC
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english', ngram_range=(1,2))
 
Severe_toxic_col=X_train.severe_toxic
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Severe_toxic_col.shape)
clf= naive_bayes.MultinomialNB()
clf.fit(x,Severe_toxic_col)
z=cv.transform(X_test.comment_text)
Severe_toxic_pred=clf.predict(z)
print(Severe_toxic_pred)
print(sum(Severe_toxic_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)
[0 0 0 ... 0 0 0]
125


## OBSCENE

In [169]:
y = df.obscene
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2, random_state = 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING OBSCENE
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english', ngram_range=(1,2))
Obscene_col=X_train.obscene
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Obscene_col.shape)
clf= naive_bayes.MultinomialNB()
clf.fit(x,Obscene_col)
z=cv.transform(X_test.comment_text)
Obscene_pred=clf.predict(z)
print(Obscene_pred)
print(sum(Obscene_pred))


(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)
[0 0 0 ... 0 0 0]
678


## THREAT

In [172]:
y = df.threat
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2, random_state =5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR THREAT
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english', ngram_range=(1,2))
Threat_col=X_train.threat
x=cv.fit_transform(X_train.comment_text)
 
print(x.shape)
print(Threat_col.shape)
 
clf= naive_bayes.MultinomialNB()
clf.fit(x,Threat_col)
z=cv.transform(X_test.comment_text)
Threat_pred=clf.predict(z)
print(Threat_pred)
print(sum(Threat_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)
[0 0 0 ... 0 0 0]
10


## INSULT

In [173]:
y = df.insult
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state= 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR INSULT
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',ngram_range=(1,2))
Insult_col=X_train.insult
x=cv.fit_transform(X_train.comment_text)
 
print(x.shape)
print(Insult_col.shape)
 
clf= naive_bayes.MultinomialNB()
clf.fit(x,Insult_col)
z=cv.transform(X_test.comment_text)
Insult_pred=clf.predict(z)
print(Insult_pred)
print(sum(Insult_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)
[0 0 0 ... 0 0 0]
543


## IDENTITY HATE

In [214]:
y = df.identity_hate
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state=5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR IDENTITY HATE
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',ngram_range=(1,2))
Identity_hate_col=X_train.identity_hate
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Identity_hate_col.shape)
 
clf = naive_bayes.MultinomialNB()
clf.fit(x,Identity_hate_col)
z=cv.transform(X_test.comment_text)
Identity_hate_pred=clf.predict(z)
print(Identity_hate_pred)
#Total no. of Identity hate comments predicted
print(sum(Identity_hate_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 2373170)
(127656,)
[0 0 0 ... 0 0 0]
23


## Converting into DataFrame format

In [175]:
Toxic=pd.DataFrame(Toxic_pred)
Severe_Toxic=pd.DataFrame(Severe_toxic_pred)
Obscene=pd.DataFrame(Obscene_pred)
Threat=pd.DataFrame(Threat_pred)
Insult=pd.DataFrame(Insult_pred)
Identity_hate=pd.DataFrame(Identity_hate_pred)

## Concatnating different columns

In [180]:
Final_pred=pd.concat([Toxic,Severe_Toxic,Obscene,Threat,Insult,Identity_hate],axis=1, ignore_index = True)

## Changing Column names for Final_pred

In [182]:
print(Final_pred)

       toxic  severe_toxic  obscene  threat  insult  identity_hate
0          0             0        0       0       0              0
1          0             0        0       0       0              0
2          0             0        0       0       0              0
3          0             0        0       0       0              0
4          0             0        0       0       0              0
5          0             0        0       0       0              0
6          0             0        0       0       0              0
7          0             0        0       0       0              0
8          0             0        0       0       0              0
9          0             0        0       0       0              0
10         0             0        0       0       0              0
11         0             0        0       0       0              0
12         0             0        0       0       0              0
13         0             0        0       0       0           

In [183]:
Final_pred.columns = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

## Saving it into a csv File as "Final_Prediction"

In [191]:
Final_pred.to_csv('Final_Prediction1.csv')

#### Results Without ngram

##### COMPARING NGRAM RESULTS V/S NON NGRAM RESULTS (Count of toxicity for every column)
TOXIC Ngram Toxic =13259 Without Ngram =26263
SEVERE TOXIC Ngram Toxic = 1192 Without Ngram =4476
OBSCENE Ngram Toxic = 6997 Without Ngram =16454
THREAT Ngram Toxic =122 Without Ngram =1101
INSULT Ngram Toxic = 15090 Without Ngram =14334
IDENTITY HATE Ngram Toxic = 318 Without Ngram =2553

In [215]:
testData = X_test[['toxic','severe_toxic','obscene','threat','insult','identity_hate']]

In [186]:
testData

toxic  severe_toxic  obscene  threat  insult  identity_hate
38367       1             0        1       0       1              0
81965       0             0        0       0       0              0
23037       0             0        0       0       0              0
40710       0             0        0       0       0              0
30075       0             0        0       0       0              0
76368       0             0        0       0       0              0
67945       0             0        0       0       0              0
121171      0             0        0       0       0              0
28014       0             0        0       0       0              0
133798      0             0        0       0       0              0
110465      0             0        0       0       0              0
51974       0             0        0       0       0              0
128264      1             0        0       0       1              0
17581       0             0        0       0       0              0
1589        0             0        0       0       0              0
96648       0             0        0       0       0              0
153277      0             0        0       0       0              0
43004       0             0        0       0       0              0
56604       0             0        0       0       0              0
127681      0             0        0       0       0              0
113639      0             0        0       0       0              0
125607      0             0        0       0       0              0
9887        0             0        0       0       0              0
88973       1             0        0       0       0              0
3576        0             0        0       0       0              0
16527       0             0        0       0       0              0
4581        1             0        0       0       1              0
32063       0             0        0       0       0              0
51030       0             0        0       0       0              0
9213        0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
17216       0             0        0       0       0              0
77027       0             0        0       0       0              0
140639      0             0        0       0       0              0
35196       1             0        0       0       0              0
96992       0             0        0       0       0              0
65575       0             0        0       0       0              0
90643       0             0        0       0       0              0
71452       1             0        0       0       1              0
81365       0             0        0       0       0              0
8329        0             0        0       0       0              0
86845       0             0        0       0       0              0
40015       0             0        0       0       0              0
100216      0             0        0       0       0              0
141024      0             0        0       0       0              0
123515      0             0        0       0       0              0
113274      0             0        0       0       0              0
80009       0             0        0       0       0              0
22695       0             0        0       0       0              0
47156       0             0        0       0       0              0
86032       0             0        0       0       0              0
5042        0             0        0       0       0              0
97176       0             0        0       0       0              0
137083      0             0        0       0       0              0
68760       1             0        0       0       1              0
145259      0             0        0       0       0              0
12563       0             0        0       0       0              0
94312       0             0        0       0       0            

In [196]:
testData.columns

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [197]:
testData.shape

(31915, 6)

In [198]:
Final_pred.shape

(31915, 6)

In [200]:
Final_pred.to_csv('Final_Prediction_Toxic_comment.csv')

# ACCURACY

In [210]:
from sklearn.metrics import accuracy_score
Accuracy=accuracy_score(testData,Final_pred)
print('Final Accuracy is :{} %'.format(Accuracy*100)
                        

Final Accuracy is :90.93843020523265 %


# SIMILARITY

In [211]:
from sklearn.metrics import jaccard_similarity_score
Similarity=jaccard_similarity_score(Final_pred, testData)
print('Final Similarity Score is :{} %'.format(Similarity*100))

Final Similarity Score is :92.24335474437308 %


# Now For non n-gram Naive Bayes

# Toxic

In [217]:
y = df.toxic
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state= 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
####PREDICTING SEVERE TOXIC
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
 
Toxic_col=X_train.toxic
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Toxic_col.shape)
clf= naive_bayes.MultinomialNB()
clf.fit(x,Toxic_col)
z=cv.transform(X_test.comment_text)
Toxic_pred=clf.predict(z)
print(Toxic_pred)
print(sum(Toxic_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[1 0 0 ... 0 0 0]
2231


# Severe Toxic

In [218]:
y = df.severe_toxic
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state= 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
####PREDICTING SEVERE TOXIC
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
 
Severe_toxic_col=X_train.severe_toxic
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Severe_toxic_col.shape)
clf= naive_bayes.MultinomialNB()
clf.fit(x,Severe_toxic_col)
z=cv.transform(X_test.comment_text)
Severe_toxic_pred=clf.predict(z)
print(Severe_toxic_pred)
print(sum(Severe_toxic_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[0 0 0 ... 0 0 0]
322


# Obscene

In [219]:
y = df.obscene
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2, random_state = 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING OBSCENE
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
Obscene_col=X_train.obscene
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Obscene_col.shape)
clf= naive_bayes.MultinomialNB()
clf.fit(x,Obscene_col)
z=cv.transform(X_test.comment_text)
Obscene_pred=clf.predict(z)
print(Obscene_pred)
print(sum(Obscene_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[0 0 0 ... 0 0 0]
1354


# Threat

In [220]:
y = df.threat
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2, random_state =5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR THREAT
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
Threat_col=X_train.threat
x=cv.fit_transform(X_train.comment_text)
 
print(x.shape)
print(Threat_col.shape)
 
clf= naive_bayes.MultinomialNB()
clf.fit(x,Threat_col)
z=cv.transform(X_test.comment_text)
Threat_pred=clf.predict(z)
print(Threat_pred)
print(sum(Threat_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[0 0 0 ... 0 0 0]
33


# Insult

In [221]:
y = df.insult
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state= 5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR INSULT
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
Insult_col=X_train.insult
x=cv.fit_transform(X_train.comment_text)
 
print(x.shape)
print(Insult_col.shape)
 
clf= naive_bayes.MultinomialNB()
clf.fit(x,Insult_col)
z=cv.transform(X_test.comment_text)
Insult_pred=clf.predict(z)
print(Insult_pred)
print(sum(Insult_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[0 0 0 ... 0 0 0]
1220


# Identity Hate

In [222]:
y = df.identity_hate
X_train, X_test, y_train, y_test = train_test_split(df,y, test_size=0.2,random_state=5)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
###PREDICTING FOR IDENTITY HATE
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
Identity_hate_col=X_train.identity_hate
x=cv.fit_transform(X_train.comment_text)
print(x.shape)
print(Identity_hate_col.shape)
 
clf = naive_bayes.MultinomialNB()
clf.fit(x,Identity_hate_col)
z=cv.transform(X_test.comment_text)
Identity_hate_pred=clf.predict(z)
print(Identity_hate_pred)
#Total no. of Identity hate comments predicted
print(sum(Identity_hate_pred))

(127656, 7) (127656,)
(31915, 7) (31915,)
(127656, 165188)
(127656,)
[0 0 0 ... 0 0 0]
119


# Converting Into DataFrame

In [226]:
Toxic=pd.DataFrame(Toxic_pred)
Severe_Toxic=pd.DataFrame(Severe_toxic_pred)
Obscene=pd.DataFrame(Obscene_pred)
Threat=pd.DataFrame(Threat_pred)
Insult=pd.DataFrame(Insult_pred)
Identity_hate=pd.DataFrame(Identity_hate_pred)

In [227]:
Final_pred2=pd.concat([Toxic,Severe_Toxic,Obscene,Threat,Insult,Identity_hate],axis=1, ignore_index = True)

In [228]:
Final_pred2.columns = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

In [229]:
Final_pred2.to_csv('Final_Prediction2.csv')

# Test Data Now

In [230]:
testData = X_test[['toxic','severe_toxic','obscene','threat','insult','identity_hate']]

In [231]:
testData.shape

(31915, 6)

In [233]:
Final_pred2.shape

(31915, 6)

# Accuracy without N-Gram

In [234]:
from sklearn.metrics import accuracy_score
Accuracy1=accuracy_score(testData,Final_pred2)
print('Final Accuracy is :{} %'.format(Accuracy1*100))

Final Accuracy is :90.86949710167633 %


# Similarity without N-Gram

In [235]:
from sklearn.metrics import jaccard_similarity_score
Similarity1=jaccard_similarity_score(Final_pred2, testData)
print('Final Similarity Score is :{} %'.format(Similarity1*100))

Final Similarity Score is :92.96762233014779 %


# KNN(K- Nearest Neighbours)

## Support Vector Machines